---
num_plan: 5
camera_x: 1.5
camera_z: 2.4
camera_yaws: [0,-30,30]
seg_channels: [4,6,7,10,18]
seg_weight: 0.05
imagenet_pretrained: True
log_wandb: True
noise_collect: False
x_jitter: 3
a_jitter: 15
crop_top: 8
crop_bottom: 8
bev_model_dir: [PATH TO PRIVILEGED MODELS]
rgb_model_dir: [PATH TO PHASE MODELS]
main_data_dir: [PATH TO DATA]
